### ISSUE TITLE
BGT Extract: Error verwijderen .gfs 

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#226]
In versie NLExtract 4.okt.17 18:00 laatste versie Stetl. Als ik een BGT .zip (test file uit PDOK via kaart selector) file inlees gaat het heel lang goed, alleen krijg ik, denk laatste `.gml`, een foutmelding uit `execoutput.py` :  `No such file or directory: 'temp/imgeo-tmp.gfs'` bij verwijderen .gfs uit temp dir:

```
nusa:etl just$ ./etl-imgeo.sh 
2017-10-04 17:50:16,260 util INFO Found cStringIO, good!
2017-10-04 17:50:16,302 util INFO Found lxml.etree, native XML parsing, fabulous!
2017-10-04 17:50:16,381 util INFO Found GDAL/OGR Python bindings, super!!
2017-10-04 17:50:16,403 main INFO Stetl version = 1.1.0rc4
2017-10-04 17:50:16,404 main INFO Found args file at: options/nusa.args
2017-10-04 17:50:16,405 ETL INFO INIT - Stetl version is 1.1.0rc4
2017-10-04 17:50:16,405 ETL INFO Config/working dir = /Users/just/project/ogg/nlextract/git/bgt/etl/conf
2017-10-04 17:50:16,405 ETL INFO Reading config_file = conf/etl-imgeo-v2.1.1.cfg
2017-10-04 17:50:16,405 ETL INFO Substituting 15 args in config file from args_dict: OrderedDict([('__name__', 'asection'), ('input_dir', 'test/input'), ('zip_files_pattern', '*.[zZ][iI][pP]'), ('filename_match', '*.gml'), ('temp_dir', 'temp'), ('gfs_template', 'gfs/imgeo-v2.1.1.gfs'), ('host', 'localhost'), ('port', '5432'), ('user', 'postgres'), ('password', 'postgres'), ('database', 'bgt'), ('schema', 'test'), ('multi_opts', '-fieldTypeToString StringList'), ('spatial_extent', ''), ('max_features', '20000')])
2017-10-04 17:50:16,406 ETL INFO Substituting args OK
2017-10-04 17:50:16,407 ETL INFO START
2017-10-04 17:50:16,407 util INFO Timer start: total ETL
2017-10-04 17:50:16,407 chain INFO Assembling Chain: input_sql_pre|schema_name_filter|output_postgres...
2017-10-04 17:50:16,758 util INFO Found cStringIO, good!
2017-10-04 17:50:16,758 util INFO Found lxml.etree, native XML parsing, fabulous!
2017-10-04 17:50:16,759 util INFO Found GDAL/OGR Python bindings, super!!
2017-10-04 17:50:16,764 input INFO cfg = {'class': 'inputs.fileinput.StringFileInput', 'file_path': 'sql/drop-tables-v2.1.1.sql,sql/create-schema.sql'}
2017-10-04 17:50:16,764 fileinput INFO file_list=['sql/drop-tables-v2.1.1.sql', 'sql/create-schema.sql']
2017-10-04 17:50:16,784 output INFO cfg = {'database': 'bgt', 'class': 'outputs.dboutput.PostgresDbOutput', 'host': 'localhost', 'user': 'postgres', 'password': 'postgres', 'port': '5432', 'schema': 'test'}
2017-10-04 17:50:16,784 chain INFO Running Chain: input_sql_pre|schema_name_filter|output_postgres
2017-10-04 17:50:16,785 fileinput INFO Read/parse for start for file=sql/drop-tables-v2.1.1.sql....
2017-10-04 17:50:16,785 fileinput INFO Read/parse ok for file=sql/drop-tables-v2.1.1.sql
2017-10-04 17:50:16,785 dboutput INFO executing SQL
2017-10-04 17:50:16,785 postgis INFO Connecting to dbname=bgt user=postgres host=localhost port=5432
2017-10-04 17:50:16,846 postgis DEBUG Connected to database bgt
2017-10-04 17:50:16,860 dboutput INFO executed SQL, rowcount=-1
2017-10-04 17:50:16,860 fileinput INFO Read/parse for start for file=sql/create-schema.sql....
2017-10-04 17:50:16,860 fileinput INFO Read/parse ok for file=sql/create-schema.sql
2017-10-04 17:50:16,861 fileinput INFO all files done
2017-10-04 17:50:16,861 dboutput INFO executing SQL
2017-10-04 17:50:16,861 postgis INFO Connecting to dbname=bgt user=postgres host=localhost port=5432
2017-10-04 17:50:16,864 postgis DEBUG Connected to database bgt
2017-10-04 17:50:16,929 dboutput INFO executed SQL, rowcount=-1
2017-10-04 17:50:16,930 chain INFO DONE - 2 rounds - chain=input_sql_pre|schema_name_filter|output_postgres 
2017-10-04 17:50:16,930 chain INFO Assembling Chain: input_zip_file|extract_zip_file|parse_gml_file|xml_assembler|transformer_xslt|packet_writer|output_ogr2ogr...
2017-10-04 17:50:16,930 input INFO cfg = {'filename_pattern': '*.[zZ][iI][pP]', 'class': 'inputs.fileinput.ZipFileInput', 'file_path': 'test/input'}
2017-10-04 17:50:16,930 fileinput INFO file_list=['test/input/amersfoort.zip']
2017-10-04 17:50:16,933 xmlelementreader INFO Element tags to be matched: ['cityObjectMember']
2017-10-04 17:50:16,933 xmlassembler INFO cfg = {'max_elements': '20000', 'element_container_tag': 'CityModel', 'class': 'filters.xmlassembler.XmlAssembler', 'container_doc': '<?xml version="1.0" encoding="UTF-8"?>\n<CityModel xmlns:gml="http://www.opengis.net/gml"\nxmlns:imgeo="http://www.geostandaarden.nl/imgeo/2.1"\nxmlns:lu="http://www.opengis.net/citygml/landuse/2.0"\nxmlns:tra="http://www.opengis.net/citygml/transportation/2.0"\nxmlns:tun="http://www.opengis.net/citygml/tunnel/2.0"\nxmlns:veg="http://www.opengis.net/citygml/vegetation/2.0"\nxmlns:xlink="http://www.w3.org/1999/xlink"\nxmlns:wat="http://www.opengis.net/citygml/waterbody/2.0"\nxmlns:bri="http://www.opengis.net/citygml/bridge/2.0"\nxmlns:bui="http://www.opengis.net/citygml/building/2.0"\nxmlns:cif="http://www.opengis.net/citygml/cityfurniture/2.0"\nxmlns="http://www.opengis.net/citygml/2.0"\nxmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\nxsi:schemaLocation="http://www.geostandaarden.nl/imgeo/2.1 http://schemas.geonovum.nl/imgeo/2.1/imgeo-2.1.1.xsd">\n</CityModel>'}
2017-10-04 17:50:16,937 packetwriter INFO working dir /Users/just/project/ogg/nlextract/git/bgt/etl
2017-10-04 17:50:16,943 output INFO cfg = {'gfs_template': 'gfs/imgeo-v2.1.1.gfs', 'cleanup_input': 'True', 'dest_data_source': '"PG:dbname=bgt host=localhost port=5432 user=postgres password=postgres active_schema=test"', 'dest_format': 'PostgreSQL', 'options': '-append -gt 65536 -fieldTypeToString StringList --config PG_USE_COPY NO', 'spatial_extent': '', 'lco': '-lco LAUNDER=YES -lco PRECISION=NO', 'class': 'outputs.execoutput.Ogr2OgrExecOutput'}
2017-10-04 17:50:16,943 chain INFO Running Chain: input_zip_file|extract_zip_file|parse_gml_file|xml_assembler|transformer_xslt|packet_writer|output_ogr2ogr
2017-10-04 17:50:16,944 fileinput INFO zip file read : test/input/amersfoort.zip filecount=33
2017-10-04 17:50:16,944 fileinput INFO Pop file record: {'file_path': 'test/input/amersfoort.zip', 'name': u'bgt_bak.gml'}
2017-10-04 17:50:16,945 xmlelementreader INFO file opened : temp/fromzip-tmp.gml
2017-10-04 17:50:16,951 xmlelementreader INFO End of doc: temp/fromzip-tmp.gml elem_count=14
2017-10-04 17:50:16,952 xmlassembler INFO xmldoc ready: elms=14 total_elms=14
2017-10-04 17:50:16,955 xsltfilter INFO XSLT Transform OK
2017-10-04 17:50:16,956 packetwriter INFO writing to file temp/imgeo-tmp.gml
2017-10-04 17:50:16,956 packetwriter INFO written to temp/imgeo-tmp.gml
2017-10-04 17:50:16,957 execoutput INFO executing cmd=ogr2ogr -f PostgreSQL "PG:dbname=bgt host=localhost port=5432 user=postgres password=postgres active_schema=test" -append -gt 65536 -fieldTypeToString StringList --config PG_USE_COPY NO -lco LAUNDER=YES -lco PRECISION=NO temp/imgeo-tmp.gml
2017-10-04 17:50:18,323 execoutput INFO execute done
.
.
.
2017-10-04 17:50:33,697 fileinput INFO Pop file record: {'file_path': 'test/input/amersfoort.zip', 'name': u'bgt_straatmeubilair.gml'}
2017-10-04 17:50:33,699 xmlelementreader INFO file opened : temp/fromzip-tmp.gml
2017-10-04 17:50:33,719 xmlelementreader INFO End of doc: temp/fromzip-tmp.gml elem_count=47
2017-10-04 17:50:33,720 xmlassembler INFO xmldoc ready: elms=47 total_elms=7661
2017-10-04 17:50:33,726 xsltfilter INFO XSLT Transform OK
2017-10-04 17:50:33,726 packetwriter INFO writing to file temp/imgeo-tmp.gml
2017-10-04 17:50:33,727 packetwriter INFO written to temp/imgeo-tmp.gml
2017-10-04 17:50:33,728 execoutput INFO executing cmd=ogr2ogr -f PostgreSQL "PG:dbname=bgt host=localhost port=5432 user=postgres password=postgres active_schema=test" -append -gt 65536 -fieldTypeToString StringList --config PG_USE_COPY NO temp/imgeo-tmp.gml
2017-10-04 17:50:33,947 execoutput INFO execute done
2017-10-04 17:50:33,947 fileinput INFO Pop file record: {'file_path': 'test/input/amersfoort.zip', 'name': u'bgt_tunneldeel.gml'}
2017-10-04 17:50:33,948 xmlelementreader INFO file opened : temp/fromzip-tmp.gml
2017-10-04 17:50:33,950 xmlelementreader INFO End of doc: temp/fromzip-tmp.gml elem_count=4
2017-10-04 17:50:33,951 xmlassembler INFO xmldoc ready: elms=4 total_elms=7665
2017-10-04 17:50:33,952 xsltfilter INFO XSLT Transform OK
2017-10-04 17:50:33,952 packetwriter INFO writing to file temp/imgeo-tmp.gml
2017-10-04 17:50:33,952 packetwriter INFO written to temp/imgeo-tmp.gml
2017-10-04 17:50:33,953 execoutput INFO executing cmd=ogr2ogr -f PostgreSQL "PG:dbname=bgt host=localhost port=5432 user=postgres password=postgres active_schema=test" -append -gt 65536 -fieldTypeToString StringList --config PG_USE_COPY NO temp/imgeo-tmp.gml
2017-10-04 17:50:34,138 execoutput INFO execute done
2017-10-04 17:50:34,138 fileinput INFO Pop file record: {'file_path': 'test/input/amersfoort.zip', 'name': u'bgt_vegetatieobject.gml'}
2017-10-04 17:50:34,151 xmlelementreader INFO file opened : temp/fromzip-tmp.gml
2017-10-04 17:50:34,984 xmlelementreader INFO End of doc: temp/fromzip-tmp.gml elem_count=2112
2017-10-04 17:50:34,991 xmlassembler INFO xmldoc ready: elms=2112 total_elms=9777
2017-10-04 17:50:35,288 xsltfilter INFO XSLT Transform OK
2017-10-04 17:50:35,289 packetwriter INFO writing to file temp/imgeo-tmp.gml
2017-10-04 17:50:35,322 packetwriter INFO written to temp/imgeo-tmp.gml
2017-10-04 17:50:35,347 execoutput INFO executing cmd=ogr2ogr -f PostgreSQL "PG:dbname=bgt host=localhost port=5432 user=postgres password=postgres active_schema=test" -append -gt 65536 -fieldTypeToString StringList --config PG_USE_COPY NO temp/imgeo-tmp.gml
2017-10-04 17:50:37,222 execoutput INFO execute done
Traceback (most recent call last):
  File "../../externals/stetl/stetl/main.py", line 134, in <module>
    main()
  File "../../externals/stetl/stetl/main.py", line 126, in main
    etl.run()
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/etl.py", line 101, in run
    chain.run()
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/chain.py", line 208, in run
    packet = self.first_comp.process(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/component.py", line 185, in process
    packet = self.next.process(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/component.py", line 185, in process
    packet = self.next.process(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/component.py", line 185, in process
    packet = self.next.process(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/component.py", line 185, in process
    packet = self.next.process(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/component.py", line 185, in process
    packet = self.next.process(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/component.py", line 185, in process
    packet = self.next.process(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/component.py", line 174, in process
    packet = self.invoke(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/output.py", line 22, in invoke
    packet = self.write(packet)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/outputs/execoutput.py", line 189, in write
    self.execute(ogr2ogr_cmd, packet.data)
  File "/Users/just/project/ogg/nlextract/git/externals/stetl/stetl/outputs/execoutput.py", line 213, in execute
    os.remove(gfs_path)
OSError: [Errno 2] No such file or directory: 'temp/imgeo-tmp.gfs'
```

Vreemd, als ik `cleanup_input = False` zet in ETL config gaat het wel goed. De bestanden onder `temp/` staan er daarna nog.

**Comment by fsteggink** [comment]
Ik heb net vandaag op een branch een check d.m.v. os.path.exists ingevoerd die hierop controleert. Dat was niet voor dit issue, maar het zou wel als oplossing gebruikt kunnen worden. Wel moet de oorzaak worden opgehelderd. Ik ga dit issue niet zomaar afsluiten ;)

**Comment by fsteggink** [comment]
Het is eigenlijk al veel te lang geleden, maar trad de fout 1x op of trad hij meerdere keren op? Is hij sindsdien nog voorgekomen met andere downloads? En met welke versie (commit) van NLExtract trad deze fout op?

**Comment by fsteggink** [comment]
Ik heb een test gedaan, maar ik kan het niet reproduceren. De gebruikte commit is #2e338530.

De enige manier waarop ik het kan reproduceren is om tijdens het laden het GFS-bestand met de hand te verwijderen. Ik denk dat het een hiccup is geweest en geen structureel probleem. Dat zou me waarschijnlijk allang opgevallen zijn.

I.i.g. is het laadproces van de BGT nu behoorlijk gewijzigd en heb ik gisteren ook een wijziging in een eigen branch op execoutput.py: https://github.com/fsteggink/stetl/commit/9143c17b62cc95be0d941b4bc86a472f664590bf

Ik kan eventueel alvast een PR indienen voor os.path.exists als oplossing voor dit issue.

**Comment by fsteggink** [comment]
Leuk dat cross repo verwijzingen ook werken. Geen idee hoe lang dat al zo is ;)

**Comment by fsteggink** [comment]
@justb4 Bedankt voor het mergen van mijn PR. Ik ga dit issue nu afsluiten.
