### ISSUE TITLE
BAGv2 factory ERROR cannot create class 'stetl.inputs.fileinput.VsiZipFileInput'

### ISSUE THREAD

**Issue by sebastic** [nlextract/NLExtract#317]
`stetl` faalt bij het importeren van de BAGv2:
```
$ python3 ../../externals/stetl/bin/stetl -c conf/etl-imbag-2.1.0.cfg -a options/common.args -a options/$(hostname).arg
2021-04-23 18:09:33,928 util INFO Found lxml.etree, native XML parsing, fabulous!
2021-04-23 18:09:33,985 util INFO Found GDAL/OGR Python bindings, super!!
2021-04-23 18:09:33,988 main INFO Stetl version = 2.0
2021-04-23 18:09:33,991 main INFO Found args file at: options/common.args
2021-04-23 18:09:33,992 main INFO Found args file at: options/osiris.args
2021-04-23 18:09:33,992 ETL INFO INIT - Stetl version is 2.0
2021-04-23 18:09:33,992 ETL INFO Config/working dir = /home/bas/git/nlextract/nlextract/bagv2/etl/conf
2021-04-23 18:09:33,992 ETL INFO Reading config_file = conf/etl-imbag-2.1.0.cfg
2021-04-23 18:09:33,993 ETL INFO Substituting 17 args in config file from args_dict: ['pg_host', 'multival_opts', 'bag_input_file', 'schema', 'spatial_extent', 'pg_db', 'bag_file_ext', 'bag_obj_file_pat', 'config_opts', 'feat_per_tx', 'open_opts', 'pg_port', 'layer_creation_opts', 'srs_opts', 'pg_user', 'password', 'bag_file_wildcard']
2021-04-23 18:09:33,993 ETL INFO Substituting args OK
2021-04-23 18:09:33,993 ETL INFO START
2021-04-23 18:09:33,993 util INFO Timer start: total ETL
[...]
2021-04-23 18:09:34,175 chain INFO Assembling Chain: input_bag_leveringsdoc_file|convert_vsi_to_etree_doc|transformer_xslt_leveringsdoc|output_ogr_postgis...
2021-04-23 18:09:34,175 factory ERROR cannot create class 'stetl.inputs.fileinput.VsiZipFileInput'
2021-04-23 18:09:34,175 factory ERROR cannot create object instance from class 'stetl.inputs.fileinput.VsiZipFileInput' e=module 'stetl.inputs.fileinput' has no attribute 'VsiZipFileInput'
Traceback (most recent call last):
  File "/home/bas/git/nlextract/nlextract/bagv2/etl/../../externals/stetl/bin/stetl", line 43, in <module>
    main()
  File "/home/bas/git/nlextract/nlextract/bagv2/etl/../../externals/stetl/bin/stetl", line 36, in main
    etl.run()
  File "/usr/lib/python3/dist-packages/stetl/etl.py", line 154, in run
    chain.assemble()
  File "/usr/lib/python3/dist-packages/stetl/chain.py", line 87, in assemble
    etl_comp = factory.create_obj(self.config_dict, etl_section_name.strip())
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 28, in create_obj
    raise e
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 22, in create_obj
    class_obj = self.class_forname(class_string)
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 50, in class_forname
    raise e
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 46, in class_forname
    class_obj = getattr(
AttributeError: module 'stetl.inputs.fileinput' has no attribute 'VsiZipFileInput'
```

De Stetl 2.0 release kan niet gebruikt worden omdat de features gebruikt voor BAGv2 nog niet gereleased zijn, maar zelfs met de actuele code in git werkt het niet. Omdat code uit de geinstalleerde package alsnog gebruikt wordt.

**Comment by justb4** [comment]
Ja inderdaad moet laatste (`master`) versie van Stetl gebruikt. Wordt tijd voor nieuwe release....
Deze (laatste Stetl master-versie) zit ook als submodule in NLExtract. Misschien heb je niet laatste versie submodule?
Via `PYTHONPATH` is toch locale Stetl package/versie te omzeilen?
Als we een stabiele versie Stetl hebben zou ik ook liever de submodule niet gebruiken/uitfaseren. Enige voordeel nu is dat de submodule een "gepinde" master-versie van Stetl heeft die zeker werkt en in NLExtract distributies/releases meekomt zodat je zeker bent dat geheel werkt. Maar ook NLExtract zou mogelijk Python package kunnen worden zodat alles met pip install en dependencies kan. Daarvoor moeten we project ook weer actiever beheren: versies uitbrengen etc. Helaas zijn er op dit moment buiten ons geen actieve bijdragers...

**Comment by sebastic** [comment]
>  Via `PYTHONPATH` is toch locale Stetl package/versie te omzeilen?

Nope, dan wordt nog steeds de code uit `/usr/lib/python3/dist-packages` gebruikt:
```
$ PYTHONPATH="/home/bas/git/nlextract/nlextract/externals/stetl:/home/bas/git/nlextract/nlextract:." python3 -c 'import pprint; import sys; print("sys.path: %s" % pprint.pformat(sys.path))'
sys.path: ['',
 '/home/bas/git/nlextract/nlextract/externals/stetl',
 '/home/bas/git/nlextract/nlextract',
 '/home/bas/git/nlextract/nlextract/bagv2/etl',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/usr/local/lib/python3.9/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.9/dist-packages']
```
```
$ PYTHONPATH="/home/bas/git/nlextract/nlextract/externals/stetl:/home/bas/git/nlextract/nlextract:." python3 ../../externals/stetl/bin/stetl -c conf/etl-imbag-2.1.0.cfg -a options/common.args -a options/$(hostname).args 
2021-04-26 12:25:24,800 util INFO Found lxml.etree, native XML parsing, fabulous!
2021-04-26 12:25:24,853 util INFO Found GDAL/OGR Python bindings, super!!
2021-04-26 12:25:24,857 main INFO Stetl version = 2.0
2021-04-26 12:25:24,859 main INFO Found args file at: options/common.args
2021-04-26 12:25:24,860 main INFO Found args file at: options/osiris.args
2021-04-26 12:25:24,860 ETL INFO INIT - Stetl version is 2.0
2021-04-26 12:25:24,860 ETL INFO Config/working dir = /home/bas/git/nlextract/nlextract/bagv2/etl/conf
2021-04-26 12:25:24,860 ETL INFO Reading config_file = conf/etl-imbag-2.1.0.cfg
2021-04-26 12:25:24,860 ETL INFO Substituting 17 args in config file from args_dict: ['pg_user', 'bag_input_file', 'open_opts', 'srs_opts', 'schema', 'spatial_extent', 'bag_obj_file_pat', 'bag_file_ext', 'pg_host', 'bag_file_wildcard', 'multival_opts', 'layer_creation_opts', 'password', 'pg_db', 'feat_per_tx', 'config_opts', 'pg_port']
2021-04-26 12:25:24,860 ETL INFO Substituting args OK
2021-04-26 12:25:24,861 ETL INFO START
2021-04-26 12:25:24,861 util INFO Timer start: total ETL
2021-04-26 12:25:24,861 chain INFO Assembling Chain: input_sql_pre|output_postgres_sql...
2021-04-26 12:25:24,863 input INFO cfg = {'class': 'stetl.inputs.fileinput.StringFileInput', 'file_path': 'sql/create-schema.sql,sql/create-meta.sql,sql/create-tables.sql', 'format_args': 'schema:public'}
2021-04-26 12:25:24,863 fileinput INFO file_list=['sql/create-schema.sql', 'sql/create-meta.sql', 'sql/create-tables.sql']
2021-04-26 12:25:24,875 output INFO cfg = {'class': 'stetl.outputs.dboutput.PostgresDbOutput', 'database': 'bagv2', 'host': 'isis', 'port': '5432', 'user': '<hidden>', 'password': '<hidden>', 'schema': 'public'}
2021-04-26 12:25:24,875 chain INFO Running Chain: input_sql_pre|output_postgres_sql
2021-04-26 12:25:24,875 fileinput INFO Read/parse for start for file=sql/create-schema.sql....
2021-04-26 12:25:24,889 fileinput INFO Read/parse ok for file=sql/create-schema.sql
2021-04-26 12:25:24,890 dboutput INFO executing SQL
2021-04-26 12:25:24,890 postgis INFO Connecting to dbname=bagv2 user=bas host=isis port=5432
2021-04-26 12:25:24,922 postgis DEBUG Connected to database bagv2
2021-04-26 12:25:25,134 dboutput INFO executed SQL, rowcount=-1
2021-04-26 12:25:25,134 fileinput INFO Read/parse for start for file=sql/create-meta.sql....
2021-04-26 12:25:25,152 fileinput INFO Read/parse ok for file=sql/create-meta.sql
2021-04-26 12:25:25,152 dboutput INFO executing SQL
2021-04-26 12:25:25,152 postgis INFO Connecting to dbname=bagv2 user=bas host=isis port=5432
2021-04-26 12:25:25,163 postgis DEBUG Connected to database bagv2
2021-04-26 12:25:25,273 dboutput INFO executed SQL, rowcount=1
2021-04-26 12:25:25,273 fileinput INFO Read/parse for start for file=sql/create-tables.sql....
2021-04-26 12:25:25,284 fileinput INFO Read/parse ok for file=sql/create-tables.sql
2021-04-26 12:25:25,284 fileinput INFO all files done
2021-04-26 12:25:25,284 dboutput INFO executing SQL
2021-04-26 12:25:25,284 postgis INFO Connecting to dbname=bagv2 user=bas host=isis port=5432
2021-04-26 12:25:25,295 postgis DEBUG Connected to database bagv2
2021-04-26 12:25:29,718 dboutput INFO executed SQL, rowcount=1
2021-04-26 12:25:29,718 component INFO StringFileInput invokes=3 time(total, min, max, avg) = 0.043 0.011 0.018 0.014
2021-04-26 12:25:29,718 component INFO PostgresDbOutput invokes=3 time(total, min, max, avg) = 4.800 0.121 4.434 1.600
2021-04-26 12:25:29,718 chain INFO DONE - 3 rounds - chain=input_sql_pre|output_postgres_sql 
2021-04-26 12:25:29,718 chain INFO Assembling Chain: input_bag_leveringsdoc_file|convert_vsi_to_etree_doc|transformer_xslt_leveringsdoc|output_ogr_postgis...
2021-04-26 12:25:29,718 factory ERROR cannot create class 'stetl.inputs.fileinput.VsiZipFileInput'
2021-04-26 12:25:29,718 factory ERROR cannot create object instance from class 'stetl.inputs.fileinput.VsiZipFileInput' e=module 'stetl.inputs.fileinput' has no attribute 'VsiZipFileInput'
Traceback (most recent call last):
  File "/home/bas/git/nlextract/nlextract/bagv2/etl/../../externals/stetl/bin/stetl", line 43, in <module>
    main()
  File "/home/bas/git/nlextract/nlextract/bagv2/etl/../../externals/stetl/bin/stetl", line 36, in main
    etl.run()
  File "/usr/lib/python3/dist-packages/stetl/etl.py", line 154, in run
    chain.assemble()
  File "/usr/lib/python3/dist-packages/stetl/chain.py", line 87, in assemble
    etl_comp = factory.create_obj(self.config_dict, etl_section_name.strip())
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 28, in create_obj
    raise e
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 22, in create_obj
    class_obj = self.class_forname(class_string)
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 50, in class_forname
    raise e
  File "/usr/lib/python3/dist-packages/stetl/factory.py", line 46, in class_forname
    class_obj = getattr(
AttributeError: module 'stetl.inputs.fileinput' has no attribute 'VsiZipFileInput'
```
Alleen het verwijderen van de package laat de code uit de submodule werken.

**Comment by sebastic** [comment]
> Enige voordeel nu is dat de submodule een "gepinde" master-versie van Stetl heeft die zeker werkt en in NLExtract distributies/releases meekomt zodat je zeker bent dat geheel werk

Mijn ervaring met de BAGv2 support was dat het juist niet out-of-the-box werkt, zelfs met stetl uit git.

 * `sql/create-tables.sql` faalt omdat de postgis extensie niet (meer) bestaat.
 * `../../externals/stetl/bin/stetl` faalt omdat geen `python` in `PATH` bestaat.
 * `sql/fill-reltables.sql` faalt omdat `sql/create-tables.sql` de tabel niet aanmaakt, en de ogr2ogr de tabel aanmaakt met een ander schema:
```
bagv2=# \d+ nummeraanduiding;
                                                                   Table "public.nummeraanduiding"
          Column           |           Type           | Collation | Nullable |                    Default                    | Storage  | Stats target | Description 
---------------------------+--------------------------+-----------+----------+-----------------------------------------------+----------+--------------+-------------
 gid                       | integer                  |           | not null | nextval('nummeraanduiding_gid_seq'::regclass) | plain    |              | 
 huisnummer                | integer                  |           |          |                                               | plain    |              | 
 huisletter                | character varying        |           |          |                                               | extended |              | 
 huisnummertoevoeging      | character varying        |           |          |                                               | extended |              | 
 postcode                  | character varying        |           |          |                                               | extended |              | 
 typeadresseerbaarobject   | character varying        |           |          |                                               | extended |              | 
 openbareruimteref         | character varying        |           |          |                                               | extended |              | 
 lvid                      | character varying        |           |          |                                               | extended |              | 
 namespace                 | character varying        |           |          |                                               | extended |              | 
 lokaalid                  | character varying        |           |          |                                               | extended |              | 
 versie                    | character varying        |           |          |                                               | extended |              | 
 status                    | character varying        |           |          |                                               | extended |              | 
 geconstateerd             | boolean                  |           |          |                                               | plain    |              | 
 documentdatum             | date                     |           |          |                                               | plain    |              | 
 documentnummer            | character varying        |           |          |                                               | extended |              | 
 voorkomenidentificatie    | integer                  |           |          |                                               | plain    |              | 
 begingeldigheid           | date                     |           |          |                                               | plain    |              | 
 eindgeldigheid            | date                     |           |          |                                               | plain    |              | 
 tijdstipregistratie       | timestamp with time zone |           |          |                                               | plain    |              | 
 eindregistratie           | timestamp with time zone |           |          |                                               | plain    |              | 
 tijdstipinactief          | timestamp with time zone |           |          |                                               | plain    |              | 
 tijdstipregistratielv     | timestamp with time zone |           |          |                                               | plain    |              | 
 tijdstipeindregistratielv | timestamp with time zone |           |          |                                               | plain    |              | 
 tijdstipinactieflv        | timestamp with time zone |           |          |                                               | plain    |              | 
 tijdstipnietbaglv         | timestamp with time zone |           |          |                                               | plain    |              | 
 wkb_geometry              | geometry(Geometry,28992) |           |          |                                               | main     |              | 
Indexes:
    "nummeraanduiding_pkey" PRIMARY KEY, btree (gid)
```
```
bag=# \d+ nummeraanduiding;
                                                                     Table "public.nummeraanduiding"
           Column            |            Type             | Collation | Nullable |                    Default                    | Storage  | Stats target | Description 
-----------------------------+-----------------------------+-----------+----------+-----------------------------------------------+----------+--------------+-------------
 gid                         | integer                     |           | not null | nextval('nummeraanduiding_gid_seq'::regclass) | plain    |              | 
 identificatie               | character varying(16)       |           |          |                                               | extended |              | 
 aanduidingrecordinactief    | boolean                     |           |          |                                               | plain    |              | 
 aanduidingrecordcorrectie   | integer                     |           |          |                                               | plain    |              | 
 officieel                   | boolean                     |           |          |                                               | plain    |              | 
 inonderzoek                 | boolean                     |           |          |                                               | plain    |              | 
 begindatumtijdvakgeldigheid | timestamp without time zone |           |          |                                               | plain    |              | 
 einddatumtijdvakgeldigheid  | timestamp without time zone |           |          |                                               | plain    |              | 
 documentnummer              | character varying(20)       |           |          |                                               | extended |              | 
 documentdatum               | date                        |           |          |                                               | plain    |              | 
 huisnummer                  | numeric(5,0)                |           |          |                                               | main     |              | 
 huisletter                  | character varying(1)        |           |          |                                               | extended |              | 
 huisnummertoevoeging        | character varying(4)        |           |          |                                               | extended |              | 
 postcode                    | character varying(6)        |           |          |                                               | extended |              | 
 nummeraanduidingstatus      | nummeraanduidingstatus      |           |          |                                               | plain    |              | 
 typeadresseerbaarobject     | typeadresseerbaarobject     |           |          |                                               | plain    |              | 
 gerelateerdeopenbareruimte  | character varying(16)       |           |          |                                               | extended |              | 
 gerelateerdewoonplaats      | character varying(16)       |           |          |                                               | extended |              | 
Indexes:
    "nummeraanduiding_pkey" PRIMARY KEY, btree (gid)
    "nummeraanduiding_key" btree (identificatie, aanduidingrecordinactief, aanduidingrecordcorrectie, begindatumtijdvakgeldigheid)
    "nummeraanduiding_postcode" btree (postcode)
```

**Comment by Robkromwijk** [comment]
Ik heb https://github.com/nlextract/NLExtract/releases/tag/1.5.3 gedownload en in een virtual environment alle python afhankelijkheden met `requirements.txt` geïnstalleerd. Daarna laatste BAG-extract gedownload via `https://service.pdok.nl/kadaster/adressen/atom/v1_0/downloads/lvbag-extract-nl.zip` en uitgepakt. Dit zip-bestand bevat 11 zip-bestanden voor iedere BAG objectklasse en `Leveringsdocument-BAG-Extract.xml`

    <?xml version="1.0" encoding="UTF-8"?>
    <xb:BAG-Extract-Levering xmlns:xb="http://www.kadaster.nl/schemas/lvbag/extract-levering/v20200601" xmlns:selecties-extract="http://www.kadaster.nl/schemas/lvbag/extract-selecties/v20200601">
    <xb:SelectieGegevens>
        <selecties-extract:LVC-Extract>
            <selecties-extract:StandTechnischeDatum>2022-03-08</selecties-extract:StandTechnischeDatum>
        </selecties-extract:LVC-Extract>
        <selecties-extract:Gebied-Registratief>
            <selecties-extract:Gebied-NLD/>
        </selecties-extract:Gebied-Registratief>
    </xb:SelectieGegevens>
    <xb:SchemaInfo>
        <xb:naam>BagvsExtractDeelbestandExtractLvc-2.1.0.xsd</xb:naam>
        <xb:versie>20200601</xb:versie>
    </xb:SchemaInfo>
    </xb:BAG-Extract-Levering>

Vervolgens de verwerking gestart met `nlextract-1.5.3/bagv2/etl/etl.sh`. Echter, ik krijg soortgelijke foutmelding als in deze thread, alleen bij mij gaat het over een empty file list.

    2022-04-05 16:51:38,906 chain INFO Assembling Chain: input_bag_leveringsdoc_file|convert_vsi_to_etree_doc|transformer_xslt_leveringsdoc|output_ogr_postgis...
    2022-04-05 16:51:38,906 input INFO cfg = {'class': 'stetl.inputs.fileinput.VsiZipFileInput', 'file_path': '/Users/robkromwijk/git/basisstatistiek_bronnen/data/bagnl/20220405/lvbag-extract.nl.zip', 'name_filter': 'Leveringsdocument-BAG-Extract.xml'}
    2022-04-05 16:51:38,907 fileinput INFO file_list=[]
    2022-04-05 16:51:38,907 factory ERROR cannot create object instance from class 'stetl.inputs.fileinput.VsiZipFileInput' e=File list is empty!!

Kan hetzelfde probleem de oorzaak zijn? Of is de inhoud van `Leveringsdocument-BAG-Extract.xml` niet goed?

Alvast bedankt voor het meedenken.

**Comment by sebastic** [comment]
De error lijkt er eerder op te wijzen dat er geen `Leveringsdocument-BAG-Extract.xml` bestand in `/Users/robkromwijk/git/basisstatistiek_bronnen/data/bagnl/20220405/lvbag-extract.nl.zip` zit zoals verwacht.

Dit is de [lvbag-extract-nl.zip](https://service.pdok.nl/kadaster/adressen/atom/v1_0/downloads/lvbag-extract-nl.zip) content van 2022-03-08:
```
$ unzip -l lvbag-extract-nl.zip 
Archive:  lvbag-extract-nl.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      788  2022-03-08 09:59   Leveringsdocument-BAG-Extract.xml
    73592  2022-03-08 09:59   GEM-WPL-RELATIE-08032022.zip
947782479  2022-03-08 09:56   9999VBO08032022.zip
 20231530  2022-03-08 09:57   9999WPL08032022.zip
1638903547  2022-03-08 09:57   9999PND08032022.zip
305036339  2022-03-08 09:59   9999NUM08032022.zip
   115296  2022-03-08 09:59   9999Inactief08032022.zip
 10651308  2022-03-08 09:59   9999OPR08032022.zip
110676974  2022-03-08 09:59   9999InOnderzoek08032022.zip
  1538886  2022-03-08 09:59   9999LIG08032022.zip
 16437385  2022-03-08 09:59   9999NietBag08032022.zip
  3445666  2022-03-08 09:59   9999STA08032022.zip
---------                     -------
3054893790                     12 files
```

De filename op jouw systeem is `lvbag-extract.nl.zip` ipv `lvbag-extract-nl.zip` wat een typo in de `bag_input_file` waarde suggereerd.

**Comment by Robkromwijk** [comment]
Wat suf. Dat is het inderdaad. Dank!

**Comment by justb4** [comment]
@sebastic Kunnen we deze sluiten?

**Comment by sebastic** [comment]
De BAGv2 support werk inmiddels, ik heb nog wel een berg lokale changes om dat op mijn systeem te laten werken.

Dit issue open laten gaat daar geen verschil in maken.
