### ISSUE TITLE
Docker process fails on gemeentelijke indeling generation: openpyxl package missing

### ISSUE THREAD

**Issue by justb4** [nlextract/NLExtract#338]
Running BAGV2 ETL with latest Docker Image.

```
2021-12-22 16:04:53,505 chain INFO Assembling Chain: input_string_file|command_executor...
2021-12-22 16:04:53,506 input INFO cfg = {'class': 'stetl.inputs.fileinput.StringFileInput', 'file_path': 'data/cbs/gemeentelijke-indeling_command.txt'}
2021-12-22 16:04:53,507 fileinput INFO file_list=['data/cbs/gemeentelijke-indeling_command.txt']
2021-12-22 16:04:53,511 chain INFO Running Chain: input_string_file|command_executor
2021-12-22 16:04:53,511 fileinput INFO Read/parse for start for file=data/cbs/gemeentelijke-indeling_command.txt....
2021-12-22 16:04:53,511 fileinput INFO Read/parse ok for file=data/cbs/gemeentelijke-indeling_command.txt
2021-12-22 16:04:53,511 fileinput INFO all files done
2021-12-22 16:04:53,512 execfilter INFO executing cmd=../../bag/bin/gemeentelijke-indeling.sh --convert-to-csv -i ../../bag/db/data/gemeentelijke-indeling.xml -o data/cbs/\
gemeentelijke-indeling.csv

Traceback (most recent call last):
  File "/nlx/bag/src/gemeentelijke-indeling.py", line 47, in <module>
    import openpyxl
ModuleNotFoundError: No module named 'openpyxl'
```

Think we need to add `openpyxl` dependency to both `requirements.txt` and `python3-openpyxl` to packages used in the Dockerfile. Will try that first.

**Comment by justb4** [comment]
Ok, now the next error:
```
2021-12-22 16:25:56,117 execfilter INFO executing cmd=../../bag/bin/gemeentelijke-indeling.sh --convert-to-csv -i ../../bag/db/data/gemeentelijke-indeling.xml -o data/cbs/\
gemeentelijke-indeling.csv

Traceback (most recent call last):
  File "/nlx/bag/src/gemeentelijke-indeling.py", line 48, in <module>
    import xlrd
ModuleNotFoundError: No module named 'xlrd'
```

Fix may be similar: add `xlrd==2.0.1` to requirements and `python3-xlrd` for Dockerfile.

**Comment by sebastic** [comment]
`xlrd` is required for `gemeentelijke-indeling.py` since the switch to Python 3 (#276).

`openpyxl` is required for `gemeentelijke-indeling.py` since CBS started using the XLSX format for 2021. (#294)

**Comment by justb4** [comment]
Ok, but this was not reflected in the dependencies for both Python and Docker. Now it is, and working, so closing.
