### ISSUE TITLE
Stetl error bij BRK NLExtract

### ISSUE THREAD

**Issue by jhpoosthoek** [nlextract/NLExtract#386]
Op Ubuntu probeer ik de BRK in te laden in een PostGIS database mbv NLExtract. Ik krijg echter deze error:
```
2024-08-02 14:42:59,437 util INFO Found lxml.etree, native XML parsing, fabulous!
2024-08-02 14:42:59,485 util INFO Found GDAL/OGR Python bindings, super!!
2024-08-02 14:42:59,492 main INFO Stetl version = 2.1
2024-08-02 14:42:59,498 main INFO Found args file at: dkk.args
Traceback (most recent call last):
  File "/root/NLExtract/brk/etl/../../externals/stetl/stetl/main.py", line 158, in <module>
    main()
  File "/root/NLExtract/brk/etl/../../externals/stetl/stetl/main.py", line 140, in main
    args = parse_args(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/NLExtract/brk/etl/../../externals/stetl/stetl/main.py", line 52, in parse_args
    args_total = Util.merge_two_dicts(args_total, Util.propsfile_to_dict(arg))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/NLExtract/externals/stetl/stetl/util.py", line 162, in propsfile_to_dict
    cp.readfp(FakeSecHead(open(file_path)))
    ^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
``` 

Komt iemand deze error bekend voor?

Ik heb NLExtract via `git clone https://github.com/nlextract/NLExtract.git --recurse-submodules` gedownload, vervolgens de dependencies geinstalleerd en in de folder NLExtract/brk/etl/ het bestand dkk.args aangemaakt (n.a.v. die in de options folder). Vervolgens run ik alles via `./etl.sh dkk.args`.

**Comment by jhpoosthoek** [comment]
Ik heb het opgelost door NLExtract/externals/stetl/stetl/util.py te openen en regel 162 te veranderen in:
`cp.read_file(FakeSecHead(open(file_path)))`

**Comment by justb4** [comment]
Zie nu pas. Komt zeker bekend voor, en was in Stetl gefixed: https://github.com/geopython/stetl/blob/master/stetl/util.py .
Kan zijn dat dit niet overal is doorgekomen. Ik gebruik de NLExtract Docker image, bijna dagelijks. Dus weer even heropenen hier. Kan zijn dat submodule Stetl update voldoende is.  Misschien dat je zelf kunt kijken?

**Comment by justb4** [comment]
@jhpoosthoek Stetl submodule nu in sync met Stetl `master` branch. Je kunt nog eens proberen. Error trad dus op bij gebruik Python 3.12.

**Comment by jhpoosthoek** [comment]
Top, dat probleem is opgelost. Nu heb ik een volgend probleem, main.py stopt (Killed):
```
2024-08-07 07:23:51,799 fileinput INFO zip file read : ../../../kadastralekaart-gml-nl-nohist.zip filecount=5
2024-08-07 07:23:51,799 fileinput INFO Pop file record: {'file_path': '../../../kadastralekaart-gml-nl-nohist.zip', 'name': 'kadastralekaart_perceel.gml'}
./etl.sh: line 43: 68307 Killed                  python $STETL_HOME/stetl/main.py -c conf/etl-brk.cfg -a $options_file
``` 
Dat lijkt op deze issue https://github.com/nlextract/NLExtract/issues/310. Ik gebruik een VPS met 4GB RAM, is dat denk je de oorzaak?
